import { env } from "Y/env.mjs";
import styles from "./index.module.css";
import Head from "next/head";
import { Button, ButtonGroup } from '@chakra-ui/react'
import { type NextPage } from "next";
import { useRouter } from "next/router";
import axios from "axios";

const Home: NextPage =()=> {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>App mi negocio online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            {env.NEXT_PUBLIC_BACKEND_BASE_URL}
          </h1>
          <ButtonGroup>
            <Button colorScheme='blue' onClick={()=>{
                router.push("/login")
            }}>Inicio</Button>
            <Button colorScheme='green' onClick={()=>{
               axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/ventas`, {
                withCredentials: true,
               })
            }}>Mostrar ventas</Button>
             <Button colorScheme='purple' onClick={()=>{
               axios.post(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/ventas`,
               {
                operation_date:new Date(),
                total_amount: 2500
               },
               {
                withCredentials: true,
               })
            }}>Mostrar ventas</Button>
            <Button colorScheme='red' onClick={()=>{
               router.push("/clients/new")
            }}>Nuevo cliente</Button>
          </ButtonGroup>
          
  
        </div>
      </main>
    </>
  );
}

export default Home;
