import { env } from "Y/env.mjs";
//import styles from "./index.module.css";
import Head from "next/head";
import { Button, ButtonGroup, Card, Container, Heading, Spinner } from '@chakra-ui/react'
import { type NextPage } from "next";
import { useRouter } from "next/router";
import axios from "axios";
import { useQuery } from "@tanstack/react-query";
import VentasList from "components/entiti/ventas/VentasList";

const Home: NextPage =()=> {
  const {
        data: ventas, 
        isLoading,
      } = 
  useQuery({queryKey:["ventas"], queryFn: async ()=>{
  const res = await axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/ventas`,
  {withCredentials:true})//para que nos permite pasar a traves de Credentials
  return res.data.data //esta data.data de axios
  }})

  const router = useRouter()
  return (
    <Container mt={8}>
     
       <Button
        colorScheme='blue' 
        mb={2}
        onClick={()=>{
                router.push("/login")
            }}>Inicio</Button>
      <Card p={4}>
        <Heading>Mis ventas</Heading>
        {isLoading ? <Spinner /> : <VentasList ventas={ventas}/>}  
      <Head>
        <title>App mi negocio online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>

          <ButtonGroup mt={6}>
           
            <Button colorScheme='green' onClick={()=>{
              router.push("/ventas/new")
            }}>Ventas</Button>
             <Button colorScheme='purple' onClick={()=>{
                router.push("/clients")
            }}>Clientes</Button>
          
          </ButtonGroup>
          
        </div>
      </main>
      </Card> 
    </Container>
  );
}

export default Home;
